### ISSUE TITLE
3.5, опечатка в решении

### ISSUE THREAD

**Issue by olyagnilova** [bdemeshev/em_pset#36]
Опечатка в значении F-статистики (в решениях _Fobs = 17.58_):

![img_7043](https://user-images.githubusercontent.com/23439334/33527022-753bb0be-d85a-11e7-9a9b-01d8961a4987.JPG)

Тогда статистический вывод тоже поменяется.

**Comment by bdemeshev** [comment]
Исправил, Оля, спасибо!

Пока с графиками никак завал не разберу :)
